language: csharp
branches:
  only:
    - master
    - dev
os:
  - linux
# .NET CLI require Ubuntu 14.04
dist: trusty
# Ensure that .NET Core is installed
dotnet: 2.1.104
# Ensure Mono is installed
# mono: latest
env:
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
    # Disable sending usage data to Microsoft
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
script:
  - ./build.sh -t TravisCI